version: "3"
services:
  kafka:
    image: confluentinc/cp-kafka
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    networks:
      - kafka-network

  kafka-producer:
    build: .
    depends_on:
      - kafka
    networks:
      - kafka-network

networks:
  kafka-network:
